### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by moon0326** [php-pm/php-pm-httpkernel#139] opened 2018-09-15 12:18 UTC
Hi,

I'm trying to test php-pm with my project, but having hard time even installing the project.

I'm on PHP 7.2

This is what I did. 

1. Download Laravel 5.7.3
2. cd into laravel dir and ran ``` composer require php-pm/httpkernel-adapter```
3. I get the following error

```
  Problem 1
    - Conclusion: don't install php-pm/httpkernel-adapter 1.0.4
    - Conclusion: don't install php-pm/httpkernel-adapter 1.0.3
    - Conclusion: don't install php-pm/httpkernel-adapter 1.0.2
    - Conclusion: don't install php-pm/httpkernel-adapter 1.0.1
    - Conclusion: remove paragonie/random_compat v9.99.99
    - Installation request for php-pm/httpkernel-adapter ^1.0 -> satisfiable by php-pm/httpkernel-adapter[1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].
    - Conclusion: don't install paragonie/random_compat v9.99.99
    - php-pm/httpkernel-adapter 1.0 requires php-pm/php-pm ^1.0 -> satisfiable by php-pm/php-pm[1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].
    - php-pm/php-pm 1.0 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - php-pm/php-pm 1.0.1 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - php-pm/php-pm 1.0.2 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - php-pm/php-pm 1.0.3 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - php-pm/php-pm 1.0.4 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - Can only install one of: paragonie/random_compat[v2.0.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.10, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.11, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.12, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.13, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.14, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.15, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.16, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.17, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.4, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.5, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.6, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.7, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.8, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.9, v9.99.99].
    - Installation request for paragonie/random_compat (locked at v9.99.99) -> satisfiable by paragonie/random_compat[v9.99.99].


Installation failed, reverting ./composer.json to its original content.
```

I've also tried php 5.6, but got the similar issue.

**Comment by andig** [comment] 2018-09-15 15:09
Duplicate of your other post? Different issue?

**Comment by andig** [comment] 2018-09-16 03:17
How do you download Laravel?

**Comment by moon0326** [comment] 2018-09-16 10:06
@andig Sorry for the missing steps. I used Laravel's official installer from https://laravel.com/docs/5.7/installation

1. composer global require "laravel/installer"
2. laravel new ppmtest

**Comment by andig** [comment] 2018-09-16 10:11
Ok- I can repro this now:

    ❯ composer create-project laravel/laravel blog
    Installing laravel/laravel (v5.7.0)
      - Installing laravel/laravel (v5.7.0): Downloading (100%)
    Created project in blog
    > @php -r "file_exists('.env') || copy('.env.example', '.env');"
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 71 installs, 0 updates, 0 removals
      - Installing vlucas/phpdotenv (v2.5.1): Downloading (100%)
      - Installing symfony/css-selector (v4.1.4): Downloading (100%)
      - Installing tijsverkoyen/css-to-inline-styles (2.2.1): Loading from cache
      - Installing symfony/polyfill-php72 (v1.9.0): Downloading (100%)
      - Installing symfony/polyfill-mbstring (v1.9.0): Downloading (100%)
      - Installing symfony/var-dumper (v4.1.4): Downloading (100%)
      - Installing symfony/routing (v4.1.4): Downloading (100%)
      - Installing symfony/process (v4.1.4): Downloading (100%)
      - Installing symfony/polyfill-ctype (v1.9.0): Downloading (100%)
      - Installing symfony/http-foundation (v4.1.4): Downloading (100%)
      - Installing symfony/event-dispatcher (v4.1.4): Downloading (100%)
      - Installing psr/log (1.0.2): Loading from cache
      - Installing symfony/debug (v4.1.4): Downloading (100%)
      - Installing symfony/http-kernel (v4.1.4): Downloading (100%)
      - Installing symfony/finder (v4.1.4): Downloading (100%)
      - Installing symfony/console (v4.1.4): Downloading (100%)
      - Installing doctrine/lexer (v1.0.1): Loading from cache
      - Installing egulias/email-validator (2.1.5): Downloading (100%)
      - Installing swiftmailer/swiftmailer (v6.1.3): Downloading (100%)

I think this is the problem:

      - Installing paragonie/random_compat (v9.99.99): Downloading (100%)

...

      - Installing ramsey/uuid (3.8.0): Downloading (100%)
      - Installing psr/simple-cache (1.0.1): Loading from cache
      - Installing psr/container (1.0.0): Loading from cache
      - Installing symfony/translation (v4.1.4): Downloading (100%)
      - Installing nesbot/carbon (1.33.0): Downloading (100%)
      - Installing monolog/monolog (1.23.0): Loading from cache
      - Installing league/flysystem (1.0.47): Downloading (100%)
      - Installing erusev/parsedown (1.7.1): Loading from cache
      - Installing dragonmantank/cron-expression (v2.2.0): Downloading (100%)
      - Installing doctrine/inflector (v1.3.0): Downloading (100%)
      - Installing laravel/framework (v5.7.3): Downloading (100%)
      - Installing fideloper/proxy (4.0.0): Loading from cache
      - Installing nikic/php-parser (v4.0.3): Downloading (100%)
      - Installing jakub-onderka/php-console-color (0.1): Loading from cache
      - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
      - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
      - Installing psy/psysh (v0.9.8): Downloading (100%)
      - Installing laravel/tinker (v1.0.7): Loading from cache
      - Installing beyondcode/laravel-dump-server (1.2.1): Downloading (100%)
      - Installing fzaninotto/faker (v1.8.0): Downloading (100%)
      - Installing hamcrest/hamcrest-php (v2.0.0): Loading from cache
      - Installing mockery/mockery (1.1.0): Loading from cache
      - Installing filp/whoops (2.2.1): Downloading (100%)
      - Installing nunomaduro/collision (v2.0.3): Downloading (100%)
      - Installing sebastian/version (2.0.1): Loading from cache
      - Installing sebastian/resource-operations (1.0.0): Loading from cache
      - Installing sebastian/object-reflector (1.1.1): Loading from cache
      - Installing sebastian/recursion-context (3.0.0): Loading from cache
      - Installing sebastian/object-enumerator (3.0.3): Loading from cache
      - Installing sebastian/global-state (2.0.0): Loading from cache
      - Installing sebastian/exporter (3.1.0): Loading from cache
      - Installing sebastian/environment (3.1.0): Loading from cache
      - Installing sebastian/diff (3.0.1): Downloading (100%)
      - Installing sebastian/comparator (3.0.2): Downloading (100%)
      - Installing phpunit/php-timer (2.0.0): Loading from cache
      - Installing phpunit/php-text-template (1.2.1): Loading from cache
      - Installing phpunit/php-file-iterator (2.0.2): Downloading (100%)
      - Installing theseer/tokenizer (1.1.0): Loading from cache
      - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
      - Installing phpunit/php-token-stream (3.0.0): Loading from cache
      - Installing phpunit/php-code-coverage (6.0.7): Downloading (100%)
      - Installing doctrine/instantiator (1.1.0): Loading from cache
      - Installing webmozart/assert (1.3.0): Downloading (100%)
      - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
      - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
      - Installing phpdocumentor/reflection-docblock (4.3.0): Downloading (100%)
      - Installing phpspec/prophecy (1.8.0): Downloading (100%)
      - Installing phar-io/version (2.0.1): Downloading (100%)
      - Installing phar-io/manifest (1.0.3): Downloading (100%)
      - Installing myclabs/deep-copy (1.8.1): Loading from cache
      - Installing phpunit/phpunit (7.3.5): Downloading (100%)
    ...
    Writing lock file
    Generating autoload files
    > Illuminate\Foundation\ComposerScripts::postAutoloadDump
    > @php artisan package:discover
    Discovered Package: nesbot/carbon
    Discovered Package: fideloper/proxy
    Discovered Package: laravel/tinker
    Discovered Package: beyondcode/laravel-dump-server
    Discovered Package: nunomaduro/collision
    Package manifest generated successfully.
    > @php artisan key:generate
    Application key [base64:oSLaufueBI8ZdKf4UKyClU+H79bEqNI2tNDKcSf3ULA=] set successfully.

    ❯ cd blog

    ❯ composer require php-pm/httpkernel-adapter
    Using version ^1.0 for php-pm/httpkernel-adapter
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Conclusion: don't install php-pm/httpkernel-adapter 1.0.4
        - Conclusion: don't install php-pm/httpkernel-adapter 1.0.3
        - Conclusion: don't install php-pm/httpkernel-adapter 1.0.2
        - Conclusion: don't install php-pm/httpkernel-adapter 1.0.1
        - Conclusion: remove paragonie/random_compat v9.99.99
        - Installation request for php-pm/httpkernel-adapter ^1.0 -> satisfiable by php-pm/httpkernel-adapter[1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].
        - Conclusion: don't install paragonie/random_compat v9.99.99
        - php-pm/httpkernel-adapter 1.0 requires php-pm/php-pm ^1.0 -> satisfiable by php-pm/php-pm[1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].
        - php-pm/php-pm 1.0 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
        - php-pm/php-pm 1.0.1 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
        - php-pm/php-pm 1.0.2 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
        - php-pm/php-pm 1.0.3 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
        - php-pm/php-pm 1.0.4 requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
        - Can only install one of: paragonie/random_compat[v2.0.0, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.1, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.10, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.11, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.12, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.13, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.14, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.15, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.16, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.17, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.2, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.3, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.4, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.5, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.6, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.7, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.8, v9.99.99].
        - Can only install one of: paragonie/random_compat[v2.0.9, v9.99.99].
        - Installation request for paragonie/random_compat (locked at v9.99.99) -> satisfiable by paragonie/random_compat[v9.99.99].


    Installation failed, reverting ./composer.json to its original content.

**Comment by andig** [comment] 2018-09-16 10:38
Root cause is https://github.com/paragonie/random_compat#version-99999

**Closed** 2018-09-16 10:44 UTC

**Comment by moon0326** [comment] 2018-09-16 15:51
Thank you so much @andig

**Comment by andig** [comment] 2018-09-16 15:53
Thaks for bringing this up again, especially with steps to reproduce 👍🏻
